FROM node:alpine

RUN apk update \
    && apk add --virtual build-dependencies \
        build-base \
        gcc \
        wget \
        git \
        curl \
        bash \
        grep \
        --update nodejs npm

WORKDIR '/app'

COPY package.json .

RUN npm install

RUN npm install --silent --production \
    && apk del build-dependencies \
    && rm -rf /var/cache/apk/*

COPY . .

CMD ["npm", "run", "local"]